DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS POST;

CREATE TABLE USER(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT UNIQUE NOT NULL,
    PASSWORD TEXT NOT NULL
);

CREATE TABLE POST(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    AUTHOR_ID INTEGER NOT NULL,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TITLE TEXT NOT NULL,
    BODY TEXT NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES USER (ID)
);